import React, { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { motion } from 'framer-motion'
import './styles.css'
gsap.registerPlugin(ScrollTrigger)

const projects = [
  { no:'01', title:'AI-native design system', desc:'A generative AI workflow and visual system rebuilt for distributed scale, improving cross-platform rendering efficiency by 40%.', tags:['AI / UI design','Brand systems'], tone:'cyan' },
  { no:'02', title:'A million-user interaction platform', desc:'A resilient interface for a million daily users, pairing nocturnal technology with millisecond response.', tags:['Visual design','High-concurrency UX'], tone:'blue' },
  { no:'03', title:'Global medical compliance engine', desc:'A full-stack data visual language shaped by legal and medical perspectives.', tags:['Brand design','Data visualization'], tone:'violet' },
]
function Arrow(){ return <span className="arrow">↗</span> }
const SPOTLIGHT_R = 260
const BASE_IMAGE = '/nebula.png'
const REVEAL_IMAGE = 'https://images.unsplash.com/photo-1534791547706-5c5f1f4b7d5f?auto=format&fit=crop&w=2400&q=90'
const SITE_VIDEO = 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260601_110537_3a579fa0-7bbc-4d94-9d25-0e816c7840f5.mp4'
const CONTACT_EMAIL = 'hujunzhe06@gmail.com'
const CONTACT_MAILTO = `mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent('Project inquiry — HUJUNZHE')}&body=${encodeURIComponent('Hi HUJUNZHE,\n\nI would like to discuss a future-facing project.\n\nBest,\n')}`

function RevealLayer({cursorX, cursorY}){
  const canvasRef = useRef(null)
  const [mask, setMask] = useState('')
  useEffect(()=>{
    const canvas = canvasRef.current
    if(!canvas) return
    const dpr = window.devicePixelRatio || 1
    canvas.width = window.innerWidth * dpr; canvas.height = window.innerHeight * dpr
    const ctx = canvas.getContext('2d'); ctx.scale(dpr,dpr); ctx.clearRect(0,0,window.innerWidth,window.innerHeight)
    if(cursorX < -100) return
    const gradient = ctx.createRadialGradient(cursorX,cursorY,0,cursorX,cursorY,SPOTLIGHT_R)
    gradient.addColorStop(0,'rgba(255,255,255,1)'); gradient.addColorStop(.4,'rgba(255,255,255,1)'); gradient.addColorStop(.6,'rgba(255,255,255,.75)'); gradient.addColorStop(.75,'rgba(255,255,255,.4)'); gradient.addColorStop(.88,'rgba(255,255,255,.12)'); gradient.addColorStop(1,'rgba(255,255,255,0)')
    ctx.fillStyle=gradient; ctx.beginPath(); ctx.arc(cursorX,cursorY,SPOTLIGHT_R,0,Math.PI*2); ctx.fill(); setMask(`url(${canvas.toDataURL()})`)
  },[cursorX,cursorY])
  return <><canvas ref={canvasRef} className="spotlight-canvas"/><div className="reveal-layer" style={{backgroundImage:`url(${REVEAL_IMAGE})`,maskImage:mask,WebkitMaskImage:mask}}/></>
}

function ParticleText(){ return null }
function Starfield(){const ref=useRef(null);useEffect(()=>{const c=ref.current,ctx=c?.getContext('2d');if(!c||!ctx)return;let w=0,h=0,dpr=1,raf;let mouse={x:0,y:0};let stars=[];const resize=()=>{w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,2);c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(260,Math.floor(w*h/6500))},()=>({x:Math.random()*w,y:Math.random()*h,r:.4+Math.random()*1.5,a:.25+Math.random()*.7,s:.04+Math.random()*.18,p:Math.random()*6.28}))};const move=e=>{mouse.x=(e.clientX/w-.5)*18;mouse.y=(e.clientY/h-.5)*18};const draw=t=>{ctx.clearRect(0,0,w,h);stars.forEach((s,i)=>{s.y-=s.s;if(s.y<-4)s.y=h+4;const tw=s.a+.2*Math.sin(t*.0015+s.p);ctx.globalAlpha=tw;ctx.fillStyle=i%17===0?'#c8a8ff':'#fff';ctx.beginPath();ctx.arc(s.x+mouse.x*(s.r*1.5),s.y+mouse.y*(s.r*1.5),s.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;raf=requestAnimationFrame(draw)};resize();addEventListener('resize',resize);addEventListener('pointermove',move);raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);removeEventListener('pointermove',move)}},[]);return <canvas ref={ref} className="starfield" aria-hidden="true"/>}
function DepthText({text,layers=34,depth=2.4,faceColor='#f8fafc',depthColor='#7c3aed',tilt=7.5,pointerTracking=true,smoothing=.14,perspective=900,autoOrbit,orbitSpeed=.35,fontSize='clamp(3rem,12vw,7rem)',fontWeight=900,shadow=true}){
  const ref=useRef(null); const target=useRef({x:0,y:0}); const current=useRef({x:0,y:0})
  useEffect(()=>{const el=ref.current;if(!el)return;let frame;const move=e=>{if(!pointerTracking)return;const r=el.getBoundingClientRect();target.current.x=((e.clientX-(r.left+r.width/2))/r.width)*tilt;target.current.y=-((e.clientY-(r.top+r.height/2))/r.height)*tilt};const tick=t=>{if(autoOrbit&&!pointerTracking){target.current.x=Math.sin(t*.001*orbitSpeed)*tilt;target.current.y=Math.cos(t*.001*orbitSpeed)*tilt*.5}current.current.x+=(target.current.x-current.current.x)*smoothing;current.current.y+=(target.current.y-current.current.y)*smoothing;el.style.setProperty('--rx',`${current.current.y}deg`);el.style.setProperty('--ry',`${current.current.x}deg`);frame=requestAnimationFrame(tick)};window.addEventListener('pointermove',move);frame=requestAnimationFrame(tick);return()=>{window.removeEventListener('pointermove',move);cancelAnimationFrame(frame)}},[autoOrbit,orbitSpeed,pointerTracking,smoothing,tilt]);return <div ref={ref} className="depth-text" style={{'--layers':layers,'--depth':`${depth}px`,'--face':faceColor,'--depth-color':depthColor,'--perspective':`${perspective}px`,'--font-size':fontSize,'--font-weight':fontWeight,'--shadow':shadow?'1':'0'}} aria-label={text}>{Array.from({length:layers},(_,i)=><span key={i} className="depth-layer" style={{'--i':i}}>{text}</span>)}<span className="depth-face">{text}</span></div>
}
function SwarmCursor({color='#fff',accentColor='#fff',count=10,size=10,speed=2.5,spread=100,wander=.25,trail=.75,scatterOnClick,children}){const ref=useRef(null);useEffect(()=>{const box=ref.current,canvas=box?.querySelector('canvas');if(!box||!canvas)return;const ctx=canvas.getContext('2d');let w=0,h=0,raf,mouse={x:0,y:0};let dots=[];const resize=()=>{w=box.clientWidth;h=box.clientHeight;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);dots=Array.from({length:count},(_,i)=>({x:w/2,y:h/2,vx:0,vy:0,a:i*.6}))};const move=e=>{const r=box.getBoundingClientRect();mouse={x:e.clientX-r.left,y:e.clientY-r.top}};const click=()=>{if(scatterOnClick)dots.forEach(d=>{d.vx+=(Math.random()-.5)*spread*.08;d.vy+=(Math.random()-.5)*spread*.08})};const draw=t=>{ctx.fillStyle=`rgba(10,6,20,${trail})`;ctx.fillRect(0,0,w,h);dots.forEach((d,i)=>{const dx=mouse.x-d.x,dy=mouse.y-d.y;d.vx+=dx*.002+(Math.random()-.5)*wander*.08;d.vy+=dy*.002+(Math.random()-.5)*wander*.08;d.vx*=.94;d.vy*=.94;d.x+=d.vx*speed;d.y+=d.vy*speed;ctx.fillStyle=i%3===0?accentColor:color;ctx.shadowBlur=14;ctx.shadowColor=accentColor;ctx.beginPath();ctx.arc(d.x,d.y,size/2,0,Math.PI*2);ctx.fill()});raf=requestAnimationFrame(draw)};resize();window.addEventListener('resize',resize);box.addEventListener('pointermove',move);box.addEventListener('pointerdown',click);raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);box.removeEventListener('pointermove',move);box.removeEventListener('pointerdown',click)}},[accentColor,color,count,size,speed,spread,trail,wander,scatterOnClick]);return <div ref={ref} className="swarm-cursor"><canvas/><div className="swarm-content">{children}</div></div>}
 function App(){
  const [cursorPos,setCursorPos] = useState({x:-999,y:-999}); const mouse=useRef({x:-999,y:-999}); const smooth=useRef({x:-999,y:-999}); const raf=useRef()
  useEffect(()=>{ const move=e=>{mouse.current={x:e.clientX,y:e.clientY}}; const tick=()=>{smooth.current.x+=(mouse.current.x-smooth.current.x)*.1;smooth.current.y+=(mouse.current.y-smooth.current.y)*.1;setCursorPos({...smooth.current});raf.current=requestAnimationFrame(tick)}; window.addEventListener('mousemove',move);raf.current=requestAnimationFrame(tick);return()=>{window.removeEventListener('mousemove',move);cancelAnimationFrame(raf.current)} },[])
  useLayoutEffect(()=>{const ctx=gsap.context(()=>{const intro=gsap.timeline({defaults:{ease:'power4.out'}});intro.fromTo('.hero-video-overlay',{clipPath:'inset(0 0 0 0)'},{clipPath:'inset(0 0 100% 0)',duration:1.8,ease:'power4.inOut'}).fromTo('.hero .nav',{y:-40,opacity:0},{y:0,opacity:1,duration:1.1},'-=1.15').fromTo('.hero h1',{y:120,scaleY:.72,opacity:0,filter:'blur(16px)'},{y:0,scaleY:1,opacity:1,filter:'blur(0px)',duration:1.35},'-=.85').fromTo('.hero-intro,.hero .primary-button',{y:40,opacity:0},{y:0,opacity:1,duration:1,stagger:.12},'-=.7').fromTo('.stats div',{y:50,opacity:0},{y:0,opacity:1,duration:.85,stagger:.1},'-=.55');gsap.utils.toArray('.page:not(.hero) .section-bar').forEach(el=>gsap.fromTo(el,{x:-80,opacity:0},{x:0,opacity:1,duration:1.1,ease:'power4.out',scrollTrigger:{trigger:el,start:'top 86%',toggleActions:'play none none reverse'}}));gsap.utils.toArray('.page:not(.hero) .section-title').forEach(el=>gsap.fromTo(el,{y:130,scale:.72,opacity:0,clipPath:'inset(0 0 100% 0)'},{y:0,scale:1,opacity:1,clipPath:'inset(0 0 0% 0)',duration:1.25,ease:'power4.out',scrollTrigger:{trigger:el,start:'top 82%',toggleActions:'play none none reverse'}}));gsap.utils.toArray('.project-card,.strength-grid article').forEach((el,i)=>gsap.fromTo(el,{y:90,opacity:0,rotateX:8},{y:0,opacity:1,rotateX:0,duration:1.05,delay:(i%4)*.1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%',toggleActions:'play none none reverse'}}));gsap.utils.toArray('.profile-card,.about-copy').forEach((el,i)=>gsap.fromTo(el,{x:i?80:-80,opacity:0},{x:0,opacity:1,duration:1.1,ease:'power4.out',scrollTrigger:{trigger:el,start:'top 82%',toggleActions:'play none none reverse'}}));gsap.utils.toArray('.project-art').forEach(el=>{gsap.fromTo(el,{scale:1.14},{scale:1,duration:1.5,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 90%',toggleActions:'play none none reverse'}});gsap.to(el,{yPercent:-8,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:1}})});gsap.fromTo('.contact-content',{y:150,opacity:0},{y:0,opacity:1,duration:1.4,ease:'power4.out',scrollTrigger:{trigger:'.contact',start:'top 70%',toggleActions:'play none none reverse'}})},);return()=>ctx.revert()},[])
  return <main><Starfield/><motion.div className="motion-aurora" initial={{opacity:0,scale:.7}} animate={{opacity:.45,scale:1}} transition={{duration:2.4,ease:[.16,1,.3,1]}}/><video className="site-video-backdrop" autoPlay muted loop playsInline preload="auto"><source src={SITE_VIDEO} type="video/mp4"/></video><div className="site-backdrop" style={{backgroundImage:`url(${BASE_IMAGE})`}}/><SwarmCursor color="#fff" accentColor="#c58cff" count={10} size={10} speed={2.5} spread={100} wander={.25} trail={.75} scatterOnClick><span>Move through the signal</span></SwarmCursor>
  <section className="hero page" id="top"><div className="hero-image-base" style={{backgroundImage:`url(${BASE_IMAGE})`}}/><RevealLayer cursorX={cursorPos.x} cursorY={cursorPos.y}/><video className="hero-video" autoPlay muted loop playsInline><source src={SITE_VIDEO} type="video/mp4" /></video><div className="hero-video-overlay"/><div className="ambient ambient-a"/><div className="ambient ambient-b"/><nav className="nav container"><a className="brand" href="#top">HUJUNZHE<span> / 2026</span></a><div className="nav-links"><a href="#about">About</a><a href="#work">Selected Work</a><a href="#strength">Capabilities</a><a href="#contact">Contact</a></div><a className="nav-cta" href={CONTACT_MAILTO}>Let's talk <Arrow /></a></nav><div className="hero-content container"><p className="eyebrow">VISUAL / AI / BRAND DESIGNER</p><DepthText text="HUJUNZHE" layers={34} depth={2.4} faceColor="#f8fafc" depthColor="#7c3aed" tilt={7.5} pointerTracking smoothing={0.14} perspective={900} autoOrbit orbitSpeed={0.35} fontSize="clamp(3rem, 12vw, 7rem)" fontWeight={900} shadow/><h1 className="hero-subtitle"><i>Designing what is next</i><br/><span>with clarity, depth, and intent.</span></h1><p className="hero-intro">A cross-disciplinary practice shaped by law, medicine, systems thinking, and a distinctly visual point of view.</p><a className="primary-button" href="#work">Explore selected work <Arrow /></a></div><div className="stats container"><div><strong>1M+</strong><span>DAU architecture experience</span></div><div><strong>4</strong><span>Languages spoken</span></div><div><strong>Less than 1ms</strong><span>High-concurrency interaction</span></div><div><strong>100%</strong><span>Full-stack CI / CD delivery</span></div></div></section>
  <section className="about page" id="about"><div className="container"><div className="section-bar"><span>ABOUT / PROFILE</span><small>01 / Profile</small></div><ParticleText text="HUJUNZHE"/><h2 className="section-title">A hybrid mind, built across disciplines</h2><div className="about-grid"><div className="profile-card"><div className="avatar"><img src="/hujunzhe.jpg" alt="HUJUNZHE"/></div><h3>HUJUNZHE</h3><p>University of Tokyo / Dual degree</p><small>B.A. Law &amp; B.S. Medicine</small><div className="profile-line"/><small>Languages</small><div className="language-list"><b>Chinese (Native)</b><b>English (Fluent)</b><b>Japanese (N1)</b><b>Français (Advanced)</b></div></div><div className="about-copy"><p>I graduated from the University of Tokyo with dual degrees in Law and Medicine. My practice is grounded in cross-disciplinary thinking and structural problem solving.</p><p>I have led high-concurrency distributed systems, cross-platform data engines, and full-stack web and mobile products from zero to one, serving over one million daily users with millisecond retrieval and automated CI / CD.</p><p>As a visual, AI, and brand designer, I translate rigorous systems into immersive, restrained identities for ambitious technology products.</p><a className="text-link" href={CONTACT_MAILTO}>Work with HUJUNZHE <Arrow /></a></div></div></div></section>
  <section className="work page" id="work"><div className="container"><div className="section-bar"><span>SELECTED WORK</span><small>02 / Selected Work</small></div><h2 className="section-title">Selected work / systems reimagined</h2><div className="project-grid">{projects.map(p=><article className="project-card" key={p.no}><div className={`project-art ${p.tone}`}><span className="art-index">{p.no}</span><span className="art-orbit"/><span className="art-grid"/></div><div className="project-body"><h3>{p.title}</h3><p>{p.desc}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></div></section>
  <section className="strength page" id="strength"><div className="container"><div className="section-bar"><span>CAPABILITIES</span><small>03 / Capabilities</small></div><h2 className="section-title">A multidisciplinary edge</h2><div className="strength-grid"><article><b>01.</b><h3>Structural thinking across disciplines</h3><p>Dual training in law and medicine lets me deconstruct complex business needs and translate systems into precise visual language.</p></article><article><b>02.</b><h3>Full-stack systems meets AI workflows</h3><p>Fluent in React, Vite, and CI / CD, with data-engineering experience that brings generative AI naturally into the design pipeline.</p></article><article><b>03.</b><h3>Global perspective, four languages</h3><p>Four languages, cross-border collaboration, and a practice shaped by global brand launches.</p></article><article><b>04.</b><h3>Restrained, high-contrast technology aesthetics</h3><p>No templates. Just dark, immersive, high-contrast systems that make future-facing brands feel trusted.</p></article></div></div></section>
  <section className="contact page" id="contact"><div className="container"><div className="section-bar"><span>GET IN TOUCH</span><small>04 / Contact</small></div><div className="contact-content"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Start the next<br/><span>future-facing project</span></h2><p>For an AI identity, a complex system, or a good conversation, let us connect.</p><a className="email" href={CONTACT_MAILTO} aria-label={`Email HUJUNZHE at ${CONTACT_EMAIL}`}>{CONTACT_EMAIL} <Arrow /></a><a className="primary-button" href={CONTACT_MAILTO}>Send an email</a></div><footer><span>© 2026 HUJUNZHE</span><span>Tokyo · Shanghai · Everywhere</span><a href="#top">Back to top ↑</a></footer></div></section>
 </main> }
createRoot(document.getElementById('root')).render(<App />)





